version: "3.8"
services:
  app:
    image: ghcr.io/cyfamod-technologies/ghcr-php:latest
    ports:
      - "8001:80"
    environment:
      APP_ENV: production
    networks:
      - app_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        failure_action: rollback

networks:
  app_net:
    driver: overlay
